### ISSUE TITLE
Task: Implement TAK Quickstart + Usage guide to Rasenmaeher UI (v1.0)

### ISSUE THREAD

**Issue by benjamsf** [pvarki/rasenmaeher-ui#1]
PR here: https://github.com/pvarki/rasenmaeher-ui/pull/9

## Task

Implement the Services info page w/TAK, TAK Quickstart + Usage guides to Rasenmaeher UI for release 1.0. 

**Scoping decision**: at 1.0 we will directly write TAK related content to Rasenmaeher, as of there are no other products arriving in short term. We will create specification for product content served via fragments later on.

## Composition
- Services page /w TAK: Lists available services (by 1.0, TAK), see [Figma layout here](https://www.figma.com/file/nTH4hmmmmFnQGCL5IHMZfP/Tilauspalvelu-workflow?type=design&node-id=891-11458&mode=design&t=2B0MQQH2gTa7dwhG-4)
- TAK Quickstart page: Accessible from the Services page /w TAK, tells the user how to start using TAK with Android, iOS and Wintak clients. [See layout from Figma here. ](https://www.figma.com/file/nTH4hmmmmFnQGCL5IHMZfP/Tilauspalvelu-workflow?type=design&node-id=890-8096&mode=design&t=2B0MQQH2gTa7dwhG-4).
- TAK Usage Guide page: Accessible as well from the Services info page. [Figma layout here, to be finished by 1 Oct](https://www.figma.com/file/nTH4hmmmmFnQGCL5IHMZfP/Tilauspalvelu-workflow?type=design&node-id=1801-1669&mode=design&t=2B0MQQH2gTa7dwhG-4) Should tell the user the usage idea served by us. That is broken into two:
- - Fighter's usage
- - Command post usage.

## Definition of Ready
- [x] Services page w/TAK: Exists in Rasenmaeher UI
- [x] TAK Quickstart page: Exists in Rasenmaeher UI
- [x] TAK Usage Guide page: Exists in Rasenmaeher UI

## Interconnections
-[Task: Write specification for webhook endpoints that product must implement ](https://github.com/pvarki/markdown-rasenmaeher-pm/issues/32)

## Future considerations
- Feature: https://github.com/pvarki/rasenmaeher-ui/issues/10 -> Ccnsider implementation of how to get product content to Rasenmaeher UI. Per original design we want no product-specific stuff to Rasenmaeher, instead require new products to design product content by our specifications.

**Comment by benjamsf** [comment]
Implemented.
